all: start

start: main.o check.o
	$(CXX) $(CFLAGS) main.o check.o -o src/main
	./src/main

check.o:
	$(CXX) $(CFLAGS) -c src/check.cpp -o check.o

main.o:
	$(CXX) $(CFLAGS) -c src/main.cpp -o main.o

branches:
  only:
    - main
